create table Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(30) not null ,
                       email varchar(100) unique,
                       age int check ( age >0 )
);
