-- PostgreeSQL
CREATE TABLE person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);

CREATE TABLE book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);



-- MySQL
create table person (
                        id INTEGER AUTO_INCREMENT PRIMARY KEY,
                        full_name VARCHAR(124) UNIQUE,
                        birthday_year INTEGER NOT NULL
);


create table book (
                      id integer AUTO_INCREMENT PRIMARY KEY,
                      person_id INTEGER REFERENCES person(id) ON DELETE SET NULL,
                      title VARCHAR(100) NOT NULL,
                      author VARCHAR(100) NOT NULL,
                      year INTEGER NOT NULL
);

