create table Person(
                       id int generated by default as identity primary key,
                       name varchar(30) not null ,
                       email varchar(100) unique,
                       age int check ( age >0 )
);

alter table Person add column date_of_birth date;
alter table Person add column created_at timestamp;
alter table Person add column mood varchar;