create table Person(
                       id int generated by default as identity primary key,
                       name varchar(30) not null ,
                       email varchar(100) unique,
                       age int check ( age >0 )
);
create table Item(
                     id int generated by default as identity primary key,
                     item_name varchar(100)  not null,
                     person_id int references Person(id) on DELETE set null
);


